---
ID: "ba639b8a-34a5-4a8d-8b86-094b8b545fd5"
Parent: "1e6446b5-6e69-40fb-907b-2ec311d3fc36"
Template: "58119a3e-560e-4da6-97c6-1ace8a5b1219"
Path: /sitecore/system/Tasks/Commands/Pigeon/PigeonYesterday
DB: master
SharedFields:
- ID: "4bc75539-d5c4-487b-af35-ff13d62bd286"
  Hint: Method
  Value: SendYesterdays
- ID: "752579a7-ef2f-45b7-b9d1-9b682308b7a5"
  Hint: Type
  Value: Pigeon.Tasks.SendLogs, Pigeon
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "Pigeon - Yesterday's Logs"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170213T095504Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
